version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["test-requirements.txt"]
  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 120
