version: "3"
services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    restart: always
    ports:
      - 2136:2136
    hostname: localhost
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
